Resolve npm audit concerns except for those caused by azure-storage
apostrophecms/uploadfs pull request #66
Opened 2021-05-11 19:03 UTC by boutell

A fixed release of azure-storage is expected within 2 weeks and our semver rules will pick it up automatically.

There is a custom reimplementation of `mkdirp` here because of the need for node 8 bc.

Other changes made resolve issues that mocha 8 detected involving double callbacks, and eslint concerns.

2021-05-12 15:25 UTC, abea requested changes

2021-05-12 15:25 UTC, abea commented on .eslintrc
> +    "multiline-ternary": 0,
```
    "multiline-ternary": 0,
    "node/no-path-concat": 0,
```

Those two don't seem to be necessary exceptions.

2021-05-12 15:26 UTC, abea commented on .eslintrc
> +    "multiline-ternary": 0,
That would only require one path fix.

2021-05-17 17:34 UTC, boutell commented
Turned on the multiline ternary thing. The building of paths with + isn't hurting anything and I don't have a lot of bandwidth for it right now.

2021-05-17 18:24 UTC, abea reviewed
I've PR'd to remove that rule exception. #67

2021-05-18 15:08 UTC, abea approved these changes

2021-05-18 15:09 UTC, abea requested changes
we need to bump the version in package.json

2021-05-18 15:22 UTC, abea approved these changes

2021-05-18 15:24 UTC, merged